# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.47.4"
rustaceanvim = "8.0.4"
"render-markdown.nvim" = "8.11.0"
"kanagawa.nvim" = "scm"
"neo-tree.nvim" = "3.39.0"
"rocks-git.nvim" = "2.5.10"
"which-key.nvim" = "3.17.0"
nvim-window-picker = "2.4.0"
"telescope.nvim" = "scm"
"catppuccin.nvim" = { git = "catppuccin/nvim" }
"solarized.nvim" = { git = "maxmx03/solarized.nvim" }
